import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar, { MenuItem } from "@/components/ui/app/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  const home:MenuItem = { name : "Component", url : "/" }
  const menus: MenuItem[] = [
    {
      name: "About Component",
      url: "/about"
    },
    {
      name: "Component Properties",
      url: "/props"
    },
    {
      name: "Component States",
      url: "/states"
    }
  ]
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar home={home} menus={menus} />
        {children}
      </body>
    </html>
  );
}
